### PR TITLE
add_gitignore

### PR DESCRIPTION
**Pull request by AlexandruBudaca**

### CODE REVIEW

**Comment by dahfool** [comment]
@AlexandruBudaca Please find about folders and files which should be ignored for javascript projects, check other (CYF and repos) projects you work on.

**Comment by AlexandruBudaca** [comment]
Should I add the lines for the ignore files in gitignore? Thank you

**Comment by esmehm** [comment]
> Should I add the lines for the ignore files in gitignore? Thank you

You should add a line for each file / folder / file extension which you want to ignore. As Gerald says, the best starting point is by looking at a repo you've worked in before e.g. the hackathon.

The files/folders which are successfully being ignored will appear as greyed out in the folder tree on VS code, e.g. my `node_modules` folder in this screenshot 
image. You can use this as a check to make sure it's working as you expect it to be.

**Comment by AlexandruBudaca** [comment]
Thank you Esme!

**Comment by dahfool** [comment]
@AlexandruBudaca https://github.com/dahfool/soo-react-redux/blob/master/.gitignore

**Pull request merged**
